name = "egen-master-deck-api"
main = "worker.js"
compatibility_date = "2024-01-01"

# Cloudflare Workers KV namespace used by the app.
[[kv_namespaces]]
binding = "EGEN_KV"
id = "7e802b23b59b48eba67b85b876475d59"
